### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by marc365** [shoredata/GarminFMITest#1]
thanks for making this, it would be good to test but I can't build as there are some missing files:

clsApplicationFunctions.cs
clsDebugFunctions.cs
clsStringFunctions.cs

**Comment by shoredata** [comment]
I hadn't seen this message, I will add these files this weekend.

**Comment by shoredata** [comment]
I have updated the project with the missing files.  My PND is lost to the ethers of storage so I have not been able to test this.  The new source is for vs2017/.net 4.5.  I had to fix an issue with a StreamWriter where a parameter I was passing was overriding the functionality allowing a new file to be created when one did not exist.  I am glad to have you try this - definitely let me know if you have any questions.

I will leave this open for a while so you can comment on it if you decide to test it.

**Comment by marc365** [comment]
Thank you very much, the code looks good and I'll be able to test this soon...
